markdown: kramdown
url: ''
# baseurl: ''
title: Our AI Journey
description: A customizable Jekyll portfolio theme
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: sajucrajan@gmail.com
facebook_username: sajucrajan
twitter_username: sajucrajan
instagram_username: sajucrajan
linkedin_username: sajucrajan
github_username: sajucrajan
youtube_channel_id: zilnnad
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: sajucrajan
author-name: sajucrajan
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >-
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget
  pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus
  metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit.
  Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque
  sit amet sodales.
author-url: 'https://github.com/sajucrajan'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
