markdown: kramdown
url: ''
# baseurl: ''
title: Our AI Journey
description: Get your dose of AI overdrive here.
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: sajucrajan@gmail.com
facebook_username: sajucrajan
twitter_username: sajucrajan
instagram_username: sajucrajan
linkedin_username: sajucrajan
github_username: sajucrajan
youtube_channel_id: zilnnad
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: sajucrajan
author-name: sajucrajan
author-image: >-
  /assets/images/profile.png
author-about: >-
  Blah Blah Black Sheep...... Thats how it goes in AI.... 
  <b>Are we going to break out and not follow the beaten path?  Isnt that what we all want to do? Drive a Ford Bronco or a Jeep Wrangler and get offroading.
  Oh shoot.  I think I lost my way a little bit here.
author-url: 'https://github.com/sajucrajan'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
